### ISSUE TITLE
After I build the project and play,the connectsdk show me the code error. and sdk doesn;t work

### ISSUE THREAD

**Issue by LeeJongSonk** [CocosTechLabs/flappy-bird#2]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at yd (bundle.js:34:128993)
    at bundle.js:34:158386
    at Array.find (<anonymous>)
    at Object.fn (bundle.js:34:158361)
    at bundle.js:27:51812
    at si (bundle.js:27:51996)
    at ci (bundle.js:27:52524)
    at di (bundle.js:27:52899)
    at bundle.js:27:52725
    at li (bundle.js:27:52814)

function eqWalletName(wallet1, name) {
  if (!name) {
    return false;
  }
  return wallet1.name.toLowerCase() === name.toLowerCase() || wallet1.appName.toLowerCase() === name.toLowerCase();
}

**Comment by FantasyJony** [comment]
1. in editor the sdk is work.
2. In build mode this error because in the file: ```node_modules\@tonconnect\sdk\lib\esm\index.mjs``` i try patch it. it's work.
[@tonconnect+sdk+3.0.3.patch](https://github.com/user-attachments/files/16262156/%40tonconnect%2Bsdk%2B3.0.3.patch)

**Comment by LeeJongSonk** [comment]
Import using cocos creator 3.8.3 Build option configuration Target Environments > 0.5
